#!/bin/bash

# Connect to a remote ssh server 

echo "Establishing connection..." 

USERNAME=your_host
IP=your_ip

if ssh -p 2222 ${USERNAME}@${IP}; then
        echo "Success! " 
else 
        echo "Failed to connect. Please check your SSH config"
fi



